[build]
  publish = "dist"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/static/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

# Serve static files directly
[[redirects]]
  from = "/app*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/bundle.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 8080
  publish = "dist"
